PV226_Timetable/PL/Models/StopDetailViewModel.cs
using BL.DTOs.Stops;
using DAL.Entities;
using System.Collections.Generic;

namespace PL.Models
{
    public class StopDetailViewModel
    {
        public StopDTO StopDto { get; set; }

        public List<int> PhotoIds { get; set; }
    }
}

PV226_Timetable/PL/Models/StopListViewModel.cs
using BL.DTOs.Stops;
using System.Collections.Generic;

namespace PL.Models
{
    public class StopListViewModel
    {
        public IEnumerable<StopDTO> Stops { get; set; }
    }
}

PV226_Timetable/PL/Controllers/StopController.cs
using BL.DTOs.Filters;
using BL.DTOs.Stops;
using BL.Facades;
using DAL.Entities;
using PL.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace PL.Controllers
{
    [Authorize]
    public class StopController : Controller
    {
        public StopFacade StopFacade { get; set; }

        // GET: Stop
        [AllowAnonymous]
        public ActionResult Index(string name, string town)
        {
            var filter = new StopFilter()
            {
                Name = name,
                Town = town
            };

            IEnumerable<StopDTO> stopDtos = StopFacade.List(filter);

            var model = new StopListViewModel()
            {
                Stops = stopDtos
            };

            return View("StopListView", model);
        }

        // GET: Stop/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            StopDTO stopDto = StopFacade.Get(id);
            List<int> photos = StopFacade.GetPhotoIds(id);

            var model = new StopDetailViewModel()
            {
                StopDto = stopDto,
                PhotoIds = photos
            };

            return View("StopDetailView", model);
        }

        [AllowAnonymous]
        public ActionResult GetImage(int id)
        {
            Photo photo = StopFacade.GetPhoto(id);
            return File(photo.Data, "image/png");
        }

        // GET: Stop/AddPhoto
        public ActionResult AddPhoto(int stopId)
        {
            return View("AddPhotoView", new StopPhotoAddModel() { StopId = stopId });
        }

        // POST: Stop/AddPhoto
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPhoto(StopPhotoAddModel photo)
        {
            var stop = new StopDTOWihPhotos() { ID = photo.StopId };

            if (photo != null)
            {
                using (var reader = new System.IO.BinaryReader(photo.File.InputStream))
                {
                    var image = reader.ReadBytes(photo.File.ContentLength);
                    List<Photo> images = new List<Photo>();
                    images.Add(new Photo() { Data = image });
                    stop.Photos = images;
                }
                StopFacade.AddPhotos(stop);
            }
            return RedirectToAction("Index");
        }
    }
}

PV226_Timetable/PL/Views/Stop/AddPhotoView.cshtml
@model PL.Models.StopPhotoAddModel

@{
    ViewBag.Title = "Stops";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add photo to stop</h2>

@using (Html.BeginForm("AddPhoto", "Stop", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StopId)

        <div class="form-group">
            <div class="control-label col-md-2">
                <label for="file">Photo</label>
            </div>
            <div class="col-md-10">
                <input type="file" name="File" id="File" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to all stops", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PV226_Timetable/PL/Views/Stop/StopDetailView.cshtml
@model PL.Models.StopDetailViewModel

@{
    ViewBag.Title = "Stop details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stop details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StopDto.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StopDto.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StopDto.Town)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StopDto.Town)
        </dd>
        <dt>
            Photos
        </dt>
        @{
            if (Model.PhotoIds.Count == 0)
            {
                <dd>
                    <strong class="text-danger">No photos</strong>
                </dd>
            }
        }
        @foreach (var photoId in Model.PhotoIds)
        {
            <dd>
                <img src='@Url.Action("GetImage", "Stop", new { id = photoId })' />
            </dd>
        }
        @Html.ActionLink("Add photo", "AddPhoto", new { stopId = Model.StopDto.ID })
    </dl>
</div>
<div>
    @Html.ActionLink("Back to all stops", "Index")
</div>

PV226_Timetable/PL/Views/Stop/StopListView.cshtml
@model PL.Models.StopListViewModel

@{
    ViewBag.Title = "Stops";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stops</h2>
<br>

@using (Html.BeginForm("Index", "Stop", FormMethod.Get))
{
    <div>
        Name: @Html.TextBox("Name") <br>
        Town: @Html.TextBox("Town") <span>   </span>
        <input type="submit" value="Filter" class="btn btn-default" />
    </div>
}

<br>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Town
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Stops)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Town)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                </td>
            </tr>
        }
    </tbody>
</table>