PV226_Timetable/PL/Models/LinkDetailViewModel.cs
using BL.DTOs.Links;
using System;
using System.Collections.Generic;

namespace PL.Models
{
    public class LinkDetailViewModel
    {
        public LinkDTO LinkDTO { get; set; }

        public List<DateTime> LeaveTimes { get; set; }
    }
}

PV226_Timetable/PL/Models/LinkListViewModel.cs
using System.Collections.Generic;
using BL.DTOs.Links;

namespace PL.Models
{
    public class LinkListViewModel
    {
        public IEnumerable<LinkDTO> Links { get; set; }
    }
}

PV226_Timetable/PL/Controllers/LinkController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BL.DTOs.Filters;
using BL.DTOs.Links;
using BL.Facades;
using PL.Models;
using System;
using BL.Utils;

namespace PL.Controllers
{
    [Authorize(Roles = Claims.Admin)]
    public class LinkController : Controller
    {

        public LinkFacade LinkFacade { get; set; }

        // GET: Link
        [AllowAnonymous]
        public ActionResult Index(string leaveStop, string arriveStop)
        {
            var filter = new LinkFilter()
            {
                LeaveStopName = leaveStop,
                ArriveStopName = arriveStop,
                LeaveTime = DateTime.Now
            };

            IEnumerable<LinkDTO> listDtos = LinkFacade.List(filter);

            var model = new LinkListViewModel()
            {
                Links = listDtos,
            };

            return View("LinkListView", model);
        }

        // GET: Link/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            LinkDTO linkDto = LinkFacade.GetLink(id);
            return View("LinkDetailView", linkDto);
        }

        // GET: Link/EditDelay
        public ActionResult EditDelay(int id)
        {
            LinkDTO linkDto = LinkFacade.GetLink(id);
            return View("DelayEditView", linkDto);
        }

        // POST: Link/EditDelay
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDelay(LinkDTO link)
        {
            LinkDTO linkToUpdate = LinkFacade.GetLink(link.ID);
            linkToUpdate.Delay = link.Delay;

            LinkFacade.UpdateLink(linkToUpdate);
            return RedirectToAction("Index");
        }
    }
}

PV226_Timetable/PL/Views/Link/DelayEditView.cshtml
@model BL.DTOs.Links.LinkDTO

@{
    ViewBag.Title = "Edit delay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit delay</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.RouteID)
        @Html.HiddenFor(model => model.VehicleID)
        @Html.HiddenFor(model => model.LeaveTime)

        <div class="form-group">
            @Html.LabelFor(model => model.Delay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Delay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Delay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to all links", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PV226_Timetable/PL/Views/Link/LinkDetailView.cshtml
@model BL.DTOs.Links.LinkDTO

@{
    ViewBag.Title = "Link details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Link details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Leave stop
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => modelItem.Route.TwoStopRoutes.FirstOrDefault().LeaveStop.Stop.Name)
        </dd>
        <dt>
            Arrive stop
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => modelItem.Route.TwoStopRoutes.LastOrDefault().ArriveStop.Stop.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LeaveTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LeaveTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delay)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Delay)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VehicleType)
        </dd>
    </dl>
</div>

<h4>Stops</h4>

<table class="table">
    <thead>
        <tr>
            <th>
                Stop name
            </th>
            <th>
                Arrive time
            </th>
            <th>
                Leave time
            </th>
            <th>
                Kms to next stop
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Route.TwoStopRoutes.Count; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.Route.TwoStopRoutes.ElementAt(i).LeaveStop.Stop.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Route.LeaveAndArriveTimes.ElementAt(i).ArriveTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Route.LeaveAndArriveTimes.ElementAt(i).LeaveTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Route.TwoStopRoutes.ElementAt(i).LengthInKm)
                </td>
            </tr>
        }
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Route.TwoStopRoutes.LastOrDefault().ArriveStop.Stop.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Route.LeaveAndArriveTimes.LastOrDefault().ArriveTime)
            </td>
            <td></td>
        </tr>
    </tbody>
</table>

<div>
    @Html.ActionLink("Back to all links", "Index")
</div>

PV226_Timetable/PL/Views/Link/LinkListView.cshtml
@model PL.Models.LinkListViewModel

@{
    ViewBag.Title = "Links";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Links</h2>
<br>

@using (Html.BeginForm("Index", "Link", FormMethod.Get))
{
    <div>
        Leave stop: @Html.TextBox("leaveStop") <br>
        Arrive stop: @Html.TextBox("arriveStop") <span>   </span>
        @*@Html.TextBox("", Model.Links.FirstOrDefault().LeaveTime, new { @class = "datefield", type = "date" }) <span>   </span>*@
        <input type="submit" value="Filter" class="btn btn-default" />
    </div>
}

<br>
<table class="table">
    <thead>
        <tr>
            <th>
                Leave stop
            </th>
            <th>
                Arrive stop
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Links.FirstOrDefault().LeaveTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Links.FirstOrDefault().Delay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Links.FirstOrDefault().VehicleType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Links)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Route.TwoStopRoutes.FirstOrDefault().LeaveStop.Stop.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Route.TwoStopRoutes.LastOrDefault().ArriveStop.Stop.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => item.LeaveTime)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Delay) | @Html.ActionLink("Edit", "EditDelay", new { id = item.ID }) 
                </td>
                <td>
                    @Html.DisplayFor(model => item.VehicleType)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                </td>
            </tr>
        }
    </tbody>
</table>