PV226_Timetable/PL/Models/TicketListViewModel.cs
using System.Collections.Generic;
using BL.DTOs.Tickets;

namespace PL.Models
{
    public class TicketListViewModel
    {
        public IEnumerable<TicketDTO> Tickets { get; set; }
    }
}

PV226_Timetable/PL/Controllers/TicketController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BL.DTOs.Filters;
using BL.DTOs.Tickets;
using BL.Facades;
using PL.Models;

namespace PL.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        public TicketFacade TicketFacade { get; set; }
        public LinkFacade LinkFacade { get; set; }
        public StopFacade StopFacade { get; set; }

        // GET: Ticket
        public ActionResult Index(string from, string to)
        {
            var filter = new TicketFilter()
            {
                FromStopName = from,
                ToStopName = to
            };

            IEnumerable<TicketDTO> listDtos = TicketFacade.List(filter);
            var model = new TicketListViewModel()
            {
                Tickets = listDtos,
            };
            return View("TicketListView", model);
        }

        // GET: Ticket/Details/5
        public ActionResult Details(int id)
        {
            TicketDTO ticketDTO = TicketFacade.GetTicket(id);
            return View("TicketDetailView", ticketDTO);
        }

        // GET: Ticket/Create
        public ActionResult Create()
        {
            var list = StopFacade.List(new StopFilter());
            ViewBag.ShowDropDown = new SelectList(list, "ID", "Name");

            return View("TicketCreate", new TicketDTOCreate());
        }

        // POST: Ticket/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ticket/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Ticket/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ticket/Delete/5
        public ActionResult Delete(int id)
        {
            TicketDTO ticketDTO = TicketFacade.GetTicket(id);

            bool canBeCanceled = false;//TicketFacade.ReturnTicket(new ReturnTicketDTO() { CompanyID = ?});
            if (canBeCanceled)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Ticket/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PV226_Timetable/PL/Views/Ticket/TicketCreate.cshtml
@using System.Web.Mvc.Html
@using BL.DTOs.Stops
@model BL.DTOs.Tickets.TicketDTOCreate

@{
    ViewBag.Title = "Create Ticket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ticket create</h2>
<p>@ViewBag.Stops</p>

@Html.DropDownList("DROPDOWNID",(SelectList)ViewBag.ShowDropDown, "Choose stop")

@using (Html.BeginForm())
    {
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsPayed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.IsPayed, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsPayed, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FromStopID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.FromStopID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FromStopID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ToStopID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.ToStopID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ToStopID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SeatIDs, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.SeatIDs, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SeatIDs, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to ticket list", "Index")
    </div>

PV226_Timetable/PL/Views/Ticket/TicketDetailView.cshtml
@model BL.DTOs.Tickets.TicketDTO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="top-buffer-large">

        <div class="col-sm-8">
            <h3>Ticket from @Html.DisplayFor(model => model.FromStopName) to @Html.DisplayFor(model => model.ToStopName)</h3>

            <div class="container row col-sm-12 top-buffer-large ">
                <div class="col-sm-6">
                    <span class="text">Is payed:</span>
                </div>
                <div class="col-sm-6  pull-left">
                    @{
                        <label input type="checkbox">@Html.DisplayFor(model => model.IsPayed)</label>
                    }
                </div>
            </div>


            <div class="container row col-sm-12 top-buffer-large ">
                <div class="col-sm-6">
                    <span class="text">Is canceled:</span>
                </div>
                <div class="col-sm-6  pull-left">
                    @{
                        <label input type="checkbox">@Html.DisplayFor(model => model.IsCanceled)</label>
                    }
                </div>
            </div>

            <p>
                @Html.ActionLink("Back to all tickets", "Index")
            </p>
        </div>
    </div>
</div>

PV226_Timetable/PL/Views/Ticket/TicketListView.cshtml
@using BL.DTOs.Tickets
@model PL.Models.TicketListViewModel

@{
    ViewBag.Title = "Tickets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tickets</h2>
<br>

@using (Html.BeginForm("Index", "Ticket", FormMethod.Get))
{
    <div>
        From: @Html.TextBox("From") 
        To: @Html.TextBox("To") <span>   </span>
        <input type="submit" value="Filter" class="btn btn-default" />
    </div>
}

<br>
@Html.ActionLink("Buy Ticket", "Create")
<br>
<table class="table">
    <thead>
        <tr>
            <th>
                From
            </th>
            <th>
                To
            </th>
            <th>
                Price
            </th>
            <th>
                Payed
            </th>
            <th>
                Cancelled
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Tickets)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.FromStopName)
                </td>
                <td>
                    @Html.DisplayFor(model => item.ToStopName)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(model => item.IsPayed)
                </td>
                <td>
                    @Html.DisplayFor(model => item.IsCanceled)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                </td>
            </tr>
        }
    </tbody>
</table>